name: Promote Main into Test

on:
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.TEST_DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519 
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      
      - name: Checkout Test
        uses: actions/checkout@v6
        with:
          ref: test
          fetch-depth: 0
          ssh-key: ${{ secrets.TEST_DEPLOY_KEY }}

      - name: Configure Git User
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Configure Git to use SSH
        run: |
          git remote set-url origin git@github.com:ministryofjustice/laa-record-link-service.git

      - name: Test SSH connection
        run: ssh -T git@github.com || true

      - name: Print changes between main and test
        run: |
          git fetch origin main
          git fetch origin test
          echo "Changes between main and test"
          git log origin/test..origin/main --oneline --graph

      - name: Merge into Test
        run: |
          git pull origin test
          git fetch origin main
          git merge origin/main --no-ff --no-edit

          if git status | grep -q "Unmerged paths"; then
            echo "Merge Conflict. Please resolve manually"
            git merge --abort
            exit 1
          fi
          
      - name: Push to test
        run: |
          git push origin test